development:
  # Base de datos de posts
  postdb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>  # Asegúrate de que esto apunte a la dirección IP de tu base de datos en AWS RDS
    database: <%= ENV['POST_DB_NAME'] || 'postdb' %>
    sslmode: require  # Si usas SSL

  # Base de datos de responsables
  responsibledb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['RESPONSIBLE_DB_NAME'] || 'responsibledb' %>
    sslmode: require

  # Base de datos de reacciones (likes)
  reactionsdb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    database: <%= ENV['REACTIONS_DB_NAME'] || 'reactionsdb' %>
    sslmode: require

production:
  postdb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] || 'production_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'production_password' %>
    host: <%= ENV['DB_HOST'] || 'production_host' %>
    database: <%= ENV['POST_DB_NAME'] || 'postdb_production' %>
    sslmode: require
  responsibledb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] || 'production_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'production_password' %>
    host: <%= ENV['DB_HOST'] || 'production_host' %>
    database: <%= ENV['RESPONSIBLE_DB_NAME'] || 'responsibledb_production' %>
    sslmode: require
  reactionsdb:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: <%= ENV['DB_USERNAME'] || 'production_user' %>
    password: <%= ENV['DB_PASSWORD'] || 'production_password' %>
    host: <%= ENV['DB_HOST'] || 'production_host' %>
    database: <%= ENV['REACTIONS_DB_NAME'] || 'reactionsdb_production' %>
    sslmode: require
